sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.2.1"
  - development

# matrix:
#   allow_failures:
#     - haxe: development

install:
  - haxelib install hmm
  - haxelib run hmm install
  - haxelib dev abe .
  # - haxelib install travix
  # - haxelib run travix install

script:
  - haxelib run travix node
